package domain

// Plan represents the execution plan for trust configuration.
//
// A Plan is generated by the Orchestrator after the Detect phase.
// It defines which environments will be processed and which will be skipped.
//
// The Plan provides visibility into what Trustica will do before
// it actually does it. This supports the "explicit over implicit" principle.
//
// Plan is a value object - immutable after creation.
type Plan struct {
	// Targets are the environments that will be processed.
	// These environments were detected and are applicable.
	Targets []Environment

	// Skipped are the environments that will NOT be processed.
	// Each has a corresponding reason in SkipReasons.
	Skipped []Environment

	// SkipReasons maps environment IDs to the reason they were skipped.
	// Examples: "not detected", "excluded by user", "already trusted"
	SkipReasons map[string]string
}

// NewPlan creates an empty plan.
func NewPlan() *Plan {
	return &Plan{
		Targets:     make([]Environment, 0),
		Skipped:     make([]Environment, 0),
		SkipReasons: make(map[string]string),
	}
}

// AddTarget adds an environment to the list of targets to process.
func (p *Plan) AddTarget(env Environment) {
	p.Targets = append(p.Targets, env)
}

// AddSkipped adds an environment to the skipped list with a reason.
func (p *Plan) AddSkipped(env Environment, reason string) {
	p.Skipped = append(p.Skipped, env)
	p.SkipReasons[env.ID] = reason
}

// HasTargets returns true if there are environments to process.
func (p *Plan) HasTargets() bool {
	return len(p.Targets) > 0
}

// TargetCount returns the number of environments to process.
func (p *Plan) TargetCount() int {
	return len(p.Targets)
}

// SkippedCount returns the number of skipped environments.
func (p *Plan) SkippedCount() int {
	return len(p.Skipped)
}

// GetSkipReason returns the reason an environment was skipped.
// Returns empty string if the environment is not in the skipped list.
func (p *Plan) GetSkipReason(envID string) string {
	return p.SkipReasons[envID]
}
